/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Tigerar1 (https://sketchfab.com/allanromanreyes)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/jane-foster-thor-68699a6cad0f46dbaa245be040b9d0aa
Title: Jane Foster (Thor)
*/

import { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

import scene from '../assets/3d/jane_foster_thor.glb'

const Jane = ({currentAnimation, ...props}) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(scene)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    Object.values(actions).forEach((action) => action.stop());
    if(actions[currentAnimation]) {
      actions[currentAnimation].play();
    }
  },[actions, currentAnimation])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={125.818}>
          <group name="hero_janefoster01fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.thor_female}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    name="Object_9"
                    geometry={nodes.Object_9.geometry}
                    material={materials.thor_female_metal}
                    skeleton={nodes.Object_9.skeleton}
                  />
                  <skinnedMesh
                    name="Object_11"
                    geometry={nodes.Object_11.geometry}
                    material={materials.thor_female_metal}
                    skeleton={nodes.Object_11.skeleton}
                  />
                  <group name="Object_6" position={[0, 0.043, 0]} rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_8" position={[0, 0.04, 0]} rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_10" position={[0, 0.04, 0]} rotation={[-Math.PI / 2, 0, 0]} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default Jane